title: <title>
subtitle: <subtitle>
author:
  - <first author>
  # - <second author>

lang: en

mainfont: Arial
fontsize: 12pt

toc: true
toc-depth: 2
numbersections: true

geometry:
  - top=3cm
  - bottom=2cm
  - left=2cm
  - right=2cm
